---

- block:

    # active listDomainsID & defined listDefinedDomains from ansible's virt.py
    - name: check if the VM is active or defined
      virt:
        name: "{{ inventory_hostname }}"
        command: list_vms
      register: reg_kill_list_result
      failed_when: inventory_hostname not in reg_kill_list_result.list_vms
      changed_when: False

    - name: Print VMs on {{ hyper }}
      debug:
        var: reg_kill_list_result.list_vms
        verbosity: 1

    - name: destroy libvirt domain
      virt:
        name: "{{ inventory_hostname }}"
        state: destroyed

    - name: undefined libvirt domain
      virt:
        name: "{{ inventory_hostname }}"
        command: undefine

    - name: remove host from the puppetmaster
      command: "puppet cert clean {{ fqdn }}"
      args:
        removes: "/var/lib/puppet/ssl/ca/signed/{{ fqdn }}.pem"
      delegate_to: "{{ puppetmaster }}"
      when: kill_clean_puppet_cert
 
  become: yes
  delegate_to: "{{ hyper }}"

...
